name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Prepare .spoon directory for zipping
        run: |
          mkdir ../SimpleMicMute.spoon
          cp -r * ../SimpleMicMute.spoon/
          rm -rf ../SimpleMicMute.spoon/.git ../SimpleMicMute.spoon/.github

      - name: Zip Spoon directory
        run: zip -r SimpleMicMute-${GITHUB_REF_NAME}.zip ../SimpleMicMute.spoon

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: SimpleMicMute-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
